name:                icfpc2019
version:             0.1.0.0
github:              "PragyaM/icfp2019"
license:             BSD3
author:              "Thunk Tank"
maintainer:          "steve@sanityinc.com"
copyright:           "2019 Thunk Tank"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/PragyaM/icfp2019#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - parsec

library:
  source-dirs: src

executables:
  icfpc2019-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc2019

tests:
  icfpc2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc2019
